/* C code for program xpsSlave, generated by snc from ../xpsSlave.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 11 "../xpsSlave.st"
#include "XPS_C8_drivers.h"
# line 20 "../xpsSlave.st"
int xps_socket;
# line 30 "../xpsSlave.st"
static const EF_ID on_pv_mon = 1;
# line 31 "../xpsSlave.st"
static const EF_ID init_pv_mon = 2;

/* Variable declarations */
struct seqg_vars {
# line 16 "../xpsSlave.st"
	char *SNLtaskName;
# line 17 "../xpsSlave.st"
	char *ip;
# line 18 "../xpsSlave.st"
	char *master;
# line 19 "../xpsSlave.st"
	char *slave;
# line 21 "../xpsSlave.st"
	int val;
# line 22 "../xpsSlave.st"
	char *masterRdbk;
# line 23 "../xpsSlave.st"
	double ratioRdbk;
# line 27 "../xpsSlave.st"
	int debug_flag;
# line 29 "../xpsSlave.st"
	int ok_pv;
# line 30 "../xpsSlave.st"
	int on_pv;
# line 31 "../xpsSlave.st"
	int init_pv;
# line 32 "../xpsSlave.st"
	double ratio_pv;
# line 33 "../xpsSlave.st"
	double ratioRdbk_pv;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "slave_main" ******/

/* Event function for state "init" in state set "slave_main" */
static seqBool seqg_event_slave_main_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "slave_main" */
static void seqg_action_slave_main_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 42 "../xpsSlave.st"
			seqg_var->ip = seq_macValueGet(seqg_env, "IP");
# line 43 "../xpsSlave.st"
			seqg_var->master = seq_macValueGet(seqg_env, "M");
# line 44 "../xpsSlave.st"
			seqg_var->slave = seq_macValueGet(seqg_env, "S");
# line 45 "../xpsSlave.st"
			seqg_var->SNLtaskName = seq_macValueGet(seqg_env, "name");
			xps_socket = TCP_ConnectToServer(pVar->ip, 5001, 100.0);
# line 50 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 50 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 50, seqg_var->SNLtaskName, 2);
# line 50 "../xpsSlave.st"
				printf("init -> update", 0, 0, 0, 0);
# line 50 "../xpsSlave.st"
				printf("\n");
			}
# line 50 "../xpsSlave.st"
			;
# line 52 "../xpsSlave.st"
			seq_efClear(seqg_env, init_pv_mon);
# line 53 "../xpsSlave.st"
			seq_efClear(seqg_env, on_pv_mon);
		}
		return;
	}
}

/****** Code for state "update" in state set "slave_main" ******/

/* Event function for state "update" in state set "slave_main" */
static seqBool seqg_event_slave_main_0_update(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "update" in state set "slave_main" */
static void seqg_action_slave_main_0_update(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			/* C code definitions */
# line 63 "../xpsSlave.st"
			pVar->val = SingleAxisSlaveParametersGet(xps_socket, pVar->slave, pVar->masterRdbk, &pVar->ratioRdbk);
# line 64 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 64 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 64, seqg_var->SNLtaskName, 2);
# line 64 "../xpsSlave.st"
				printf("update(): val = %i, masterRdbk = %s, ratioRdbk = %f", seqg_var->val, seqg_var->masterRdbk, seqg_var->ratioRdbk, 0);
# line 64 "../xpsSlave.st"
				printf("\n");
			}
# line 64 "../xpsSlave.st"
			;
# line 67 "../xpsSlave.st"
			if (seqg_var->val == 0)
			{
				{
# line 69 "../xpsSlave.st"
					seqg_var->ok_pv = (1);
# line 69 "../xpsSlave.st"
					seq_pvPutTmo(seqg_env, 1/*ok_pv*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 69 "../xpsSlave.st"
				;
			}
			else
			{
				{
# line 73 "../xpsSlave.st"
					seqg_var->ok_pv = (0);
# line 73 "../xpsSlave.st"
					seq_pvPutTmo(seqg_env, 1/*ok_pv*/, DEFAULT, DEFAULT_TIMEOUT);
				}
# line 73 "../xpsSlave.st"
				;
			}
			{
# line 78 "../xpsSlave.st"
				seqg_var->ratioRdbk_pv = (seqg_var->ratioRdbk);
# line 78 "../xpsSlave.st"
				seq_pvPutTmo(seqg_env, 5/*ratioRdbk_pv*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 78 "../xpsSlave.st"
			;
# line 80 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 80 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 80, seqg_var->SNLtaskName, 2);
# line 80 "../xpsSlave.st"
				printf("update -> idle", 0, 0, 0, 0);
# line 80 "../xpsSlave.st"
				printf("\n");
			}
# line 80 "../xpsSlave.st"
			;
		}
		return;
	}
}

/****** Code for state "modeChange" in state set "slave_main" ******/

/* Event function for state "modeChange" in state set "slave_main" */
static seqBool seqg_event_slave_main_0_modeChange(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "modeChange" in state set "slave_main" */
static void seqg_action_slave_main_0_modeChange(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 90 "../xpsSlave.st"
			if (seqg_var->on_pv == 1)
			{
				/* C code definitions */
# line 92 "../xpsSlave.st"
				pVar->val = SingleAxisSlaveModeEnable(xps_socket, pVar->slave);
# line 93 "../xpsSlave.st"
				if (seqg_var->debug_flag >= 2)
				{
# line 93 "../xpsSlave.st"
					printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 93, seqg_var->SNLtaskName, 2);
# line 93 "../xpsSlave.st"
					printf("on_pv == 1", 0, 0, 0, 0);
# line 93 "../xpsSlave.st"
					printf("\n");
				}
# line 93 "../xpsSlave.st"
				;
			}
			else
			{
				/* C code definitions */
# line 97 "../xpsSlave.st"
				pVar->val = SingleAxisSlaveModeDisable(xps_socket, pVar->slave);
# line 98 "../xpsSlave.st"
				if (seqg_var->debug_flag >= 2)
				{
# line 98 "../xpsSlave.st"
					printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 98, seqg_var->SNLtaskName, 2);
# line 98 "../xpsSlave.st"
					printf("on_pv != 1", 0, 0, 0, 0);
# line 98 "../xpsSlave.st"
					printf("\n");
				}
# line 98 "../xpsSlave.st"
				;
			}
# line 100 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 100 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 100, seqg_var->SNLtaskName, 2);
# line 100 "../xpsSlave.st"
				printf("modeChange -> idle", 0, 0, 0, 0);
# line 100 "../xpsSlave.st"
				printf("\n");
			}
# line 100 "../xpsSlave.st"
			;
		}
		return;
	}
}

/****** Code for state "reinit" in state set "slave_main" ******/

/* Event function for state "reinit" in state set "slave_main" */
static seqBool seqg_event_slave_main_0_reinit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "reinit" in state set "slave_main" */
static void seqg_action_slave_main_0_reinit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			/* C code definitions */
# line 110 "../xpsSlave.st"
			pVar->val = SingleAxisSlaveParametersSet(xps_socket, pVar->slave, pVar->master, pVar->ratio_pv);
# line 111 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 111 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 111, seqg_var->SNLtaskName, 2);
# line 111 "../xpsSlave.st"
				printf("reinit(): val = %i", seqg_var->val, 0, 0, 0);
# line 111 "../xpsSlave.st"
				printf("\n");
			}
# line 111 "../xpsSlave.st"
			;
			{
# line 114 "../xpsSlave.st"
				seqg_var->init_pv = (0);
# line 114 "../xpsSlave.st"
				seq_pvPutTmo(seqg_env, 3/*init_pv*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 114 "../xpsSlave.st"
			;
# line 115 "../xpsSlave.st"
			seq_efClear(seqg_env, init_pv_mon);
# line 116 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 116 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 116, seqg_var->SNLtaskName, 2);
# line 116 "../xpsSlave.st"
				printf("reinit -> update", 0, 0, 0, 0);
# line 116 "../xpsSlave.st"
				printf("\n");
			}
# line 116 "../xpsSlave.st"
			;
		}
		return;
	}
}

/****** Code for state "idle" in state set "slave_main" ******/

/* Event function for state "idle" in state set "slave_main" */
static seqBool seqg_event_slave_main_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 123 "../xpsSlave.st"
	if (seq_efTestAndClear(seqg_env, on_pv_mon) && seqg_var->ok_pv == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 129 "../xpsSlave.st"
	if (seq_efTest(seqg_env, init_pv_mon))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "slave_main" */
static void seqg_action_slave_main_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 126 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 126 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 126, seqg_var->SNLtaskName, 2);
# line 126 "../xpsSlave.st"
				printf("idle -> modeChange", 0, 0, 0, 0);
# line 126 "../xpsSlave.st"
				printf("\n");
			}
# line 126 "../xpsSlave.st"
			;
		}
		return;
	case 1:
		{
# line 132 "../xpsSlave.st"
			if (seqg_var->debug_flag >= 2)
			{
# line 132 "../xpsSlave.st"
				printf("<%s,%d,%s,%d> ", "../xpsSlave.st", 132, seqg_var->SNLtaskName, 2);
# line 132 "../xpsSlave.st"
				printf("idle -> reinit", 0, 0, 0, 0);
# line 132 "../xpsSlave.st"
				printf("\n");
			}
# line 132 "../xpsSlave.st"
			;
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{R}:debug.VAL", offsetof(struct seqg_vars, debug_flag), "debug_flag", P_INT, 1, 3, 0, 1, 0, 0},
	{"{P}{R}:ok.VAL", offsetof(struct seqg_vars, ok_pv), "ok_pv", P_INT, 1, 4, 0, 0, 0, 0},
	{"{P}{R}:on.VAL", offsetof(struct seqg_vars, on_pv), "on_pv", P_INT, 1, 5, 1, 1, 0, 0},
	{"{P}{R}:init.VAL", offsetof(struct seqg_vars, init_pv), "init_pv", P_INT, 1, 6, 2, 1, 0, 0},
	{"{P}{R}:ratio.VAL", offsetof(struct seqg_vars, ratio_pv), "ratio_pv", P_DOUBLE, 1, 7, 0, 1, 0, 0},
	{"{P}{R}:ratioRdbk.VAL", offsetof(struct seqg_vars, ratioRdbk_pv), "ratioRdbk_pv", P_DOUBLE, 1, 8, 0, 0, 0, 0},
};

/* Event masks for state set "slave_main" */
static const seqMask seqg_mask_slave_main_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_slave_main_0_update[] = {
	0x00000000,
};
static const seqMask seqg_mask_slave_main_0_modeChange[] = {
	0x00000000,
};
static const seqMask seqg_mask_slave_main_0_reinit[] = {
	0x00000000,
};
static const seqMask seqg_mask_slave_main_0_idle[] = {
	0x00000016,
};

/* State table for state set "slave_main" */
static seqState seqg_states_slave_main[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_slave_main_0_init,
	/* event function */    seqg_event_slave_main_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_slave_main_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "update",
	/* action function */   seqg_action_slave_main_0_update,
	/* event function */    seqg_event_slave_main_0_update,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_slave_main_0_update,
	/* state options */     (0)
	},
	{
	/* state name */        "modeChange",
	/* action function */   seqg_action_slave_main_0_modeChange,
	/* event function */    seqg_event_slave_main_0_modeChange,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_slave_main_0_modeChange,
	/* state options */     (0)
	},
	{
	/* state name */        "reinit",
	/* action function */   seqg_action_slave_main_0_reinit,
	/* event function */    seqg_event_slave_main_0_reinit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_slave_main_0_reinit,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_slave_main_0_idle,
	/* event function */    seqg_event_slave_main_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_slave_main_0_idle,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "slave_main",
	/* states */            seqg_states_slave_main,
	/* number of states */  5
	},
};

/* Program table (global) */
seqProgram xpsSlave = {
	/* magic number */      2002001,
	/* program name */      "xpsSlave",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "name=xpsSlave,P=xxx:,R=xps:slave,IP=192.168.1.11,M=GROUP1.POSITIONER,S=GROUP2",
	/* num. event flags */  2,
	/* encoded options */   (0 | OPT_CONN | OPT_DEBUG | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void xpsSlaveRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&xpsSlave);
}
epicsExportRegistrar(xpsSlaveRegistrar);
